# Create action.yml file

name: "Notify on telegram"
description: "Send a message to a telegram chat"

inputs:
  telegram_bot_token:
    description: "Telegram bot token"
    required: true
  telegram_chat_id:
    description: "Telegram chat id"
    required: true
  message:
    description: "Message to send"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
