name: Release on tag push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js 16.x environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install npm dependencies
        run: |
          npm install

      - name: npm run build
        run: |
          npm run build

      # Create a release and upload dist folder as a release asset inside source code
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          files: dist
