name: Release on tag push

on:
  push:
    branches:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js 16.x environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install npm dependencies
        run: |
          npm install

      - name: npm run build
        run: |
          npm run build
      
      - name: Test
        uses: ./.github/workflows/test.yml
