name: "Notify on telegram"
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            "Hello world"
            "This is a multiline message"
            "This is the last line"
